begin;

-- Immutable, admin-only point-in-time versions. Daily history remains in place as a
-- second recovery layer; this table captures changes throughout the day as well.
create table if not exists private.user_state_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  captured_at timestamptz not null default now(),
  value jsonb not null,
  log_rows integer not null default 0,
  weighins integer not null default 0,
  cardio integer not null default 0,
  bytes integer not null default 0
);
create index if not exists user_state_versions_user_time_idx
  on private.user_state_versions(user_id,captured_at desc);
revoke all on private.user_state_versions from public,anon,authenticated;

create or replace function private.version_and_guard_user_state()
returns trigger language plpgsql security definer
set search_path=public,private,pg_temp
as $$
declare
  old_log integer := coalesce(jsonb_array_length(coalesce(old.value->'log','[]'::jsonb)),0);
  new_log integer := coalesce(jsonb_array_length(coalesce(new.value->'log','[]'::jsonb)),0);
  old_bw integer := coalesce(jsonb_array_length(coalesce(old.value->'bodyweight','[]'::jsonb)),0);
  new_bw integer := coalesce(jsonb_array_length(coalesce(new.value->'bodyweight','[]'::jsonb)),0);
  old_cardio integer := coalesce(jsonb_array_length(coalesce(old.value->'cardio','[]'::jsonb)),0);
  new_cardio integer := coalesce(jsonb_array_length(coalesce(new.value->'cardio','[]'::jsonb)),0);
  old_exercises integer := coalesce(jsonb_array_length(coalesce(old.value->'exercises','[]'::jsonb)),0);
  new_exercises integer := coalesce(jsonb_array_length(coalesce(new.value->'exercises','[]'::jsonb)),0);
  old_bytes integer := pg_column_size(old.value);
  new_bytes integer := pg_column_size(new.value);
begin
  if old.value is not distinct from new.value then return new; end if;

  -- Normal single-item edits/deletes pass. A sudden large collapse is rejected at the
  -- database boundary even if a stale or buggy frontend attempts a direct API update.
  if (old_log >= 20 and new_log < old_log * 0.70)
     or (old_bw >= 10 and new_bw < old_bw * 0.50)
     or (old_cardio >= 10 and new_cardio < old_cardio * 0.50)
     or (old_exercises >= 20 and new_exercises < old_exercises * 0.60)
     or (old_bytes >= 20000 and new_bytes < old_bytes * 0.45) then
    raise exception using errcode='P0001',message='STATE_SHRINK_BLOCKED';
  end if;

  insert into private.user_state_versions(user_id,value,log_rows,weighins,cardio,bytes)
  values(old.user_id,old.value,old_log,old_bw,old_cardio,old_bytes);

  delete from private.user_state_versions v
  where v.user_id=old.user_id and (
    v.captured_at < now()-interval '90 days'
    or v.id in (
      select id from private.user_state_versions
      where user_id=old.user_id order by captured_at desc offset 500
    )
  );
  return new;
end;
$$;

drop trigger if exists trg_version_and_guard_user_state on public.user_state;
create trigger trg_version_and_guard_user_state
before update on public.user_state
for each row execute function private.version_and_guard_user_state();

commit;
