-- The Lab public-launch security migration.
-- Idempotent enough to apply to the existing hosted project and complete enough to
-- document/recreate the application-owned database surface on a fresh Supabase project.

begin;

create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Application tables (CREATE IF NOT EXISTS makes this migration self-documenting
-- for a fresh Supabase project while preserving the existing production data).
-- ---------------------------------------------------------------------------

create table if not exists public.user_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_state_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  day date not null,
  value jsonb not null,
  created_at timestamptz not null default now(),
  unique (user_id, day)
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  invite_code text not null unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  emoji text not null default '💪',
  record_lifts jsonb
);

create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);
create index if not exists idx_group_members_user on public.group_members(user_id);

create table if not exists public.pro_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  since timestamptz not null default now(),
  until timestamptz
);

create table if not exists public.steps (
  user_id uuid not null references auth.users(id) on delete cascade,
  day date not null,
  count integer not null check (count >= 0 and count < 1000000),
  updated_at timestamptz not null default now(),
  primary key (user_id, day)
);

create table if not exists public.step_tokens (
  user_id uuid primary key references auth.users(id) on delete cascade,
  token uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now()
);
create unique index if not exists step_tokens_token_idx on public.step_tokens(token);

create table if not exists public.duels (
  id uuid primary key default gen_random_uuid(),
  a_id uuid not null references auth.users(id) on delete cascade,
  b_id uuid not null references auth.users(id) on delete cascade,
  a_name text not null,
  b_name text not null,
  start_day date not null,
  end_day date not null,
  created_at timestamptz not null default now(),
  status text not null default 'pending',
  days integer,
  winner_id uuid,
  cancel_req uuid,
  check (a_id <> b_id),
  check (end_day >= start_day)
);

create table if not exists public.reactions (
  group_id uuid not null references public.groups(id) on delete cascade,
  event_key text not null,
  reactor_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  reactor_name text not null,
  emoji text not null default '💪',
  created_at timestamptz not null default now(),
  primary key (group_id, event_key, reactor_id)
);

-- A public username directory without exposing real email addresses.
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[a-z0-9_]{3,20}$'),
  is_legacy boolean not null default false,
  created_at timestamptz not null default now()
);

insert into public.profiles(user_id, username, is_legacy, created_at)
select u.id,
       lower(coalesce(nullif(u.raw_user_meta_data->>'username',''), split_part(u.email,'@',1))),
       u.email like '%@lifting.local',
       coalesce(u.created_at, now())
from auth.users u
where coalesce(nullif(u.raw_user_meta_data->>'username',''), split_part(u.email,'@',1)) ~ '^[a-z0-9_]{3,20}$'
on conflict (user_id) do nothing;

-- One-time recovery codes. Plaintext codes are returned once and never stored.
create table if not exists private.backup_codes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  code_hash text not null,
  created_at timestamptz not null default now(),
  used_at timestamptz
);
create index if not exists backup_codes_user_unused_idx
  on private.backup_codes(user_id) where used_at is null;

create table if not exists private.recovery_attempts (
  identifier text primary key,
  failed_attempts integer not null default 0,
  locked_until timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists private.join_attempts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  failed_attempts integer not null default 0,
  locked_until timestamptz,
  updated_at timestamptz not null default now()
);

revoke all on all tables in schema private from public, anon, authenticated;
revoke all on all sequences in schema private from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Private helpers. These own the privileged access; exposed public RPC wrappers
-- below are SECURITY INVOKER and have narrow, explicit grants.
-- ---------------------------------------------------------------------------

create or replace function private.pro_active(target uuid)
returns boolean language sql stable security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.pro_users p
    where p.user_id = target and (p.until is null or p.until > now())
  );
$$;

create or replace function private.shares_group_with(target uuid)
returns boolean language sql stable security definer
set search_path = public, pg_temp
as $$
  select auth.uid() is not null and exists (
    select 1
    from public.group_members mine
    join public.group_members theirs on theirs.group_id = mine.group_id
    where mine.user_id = auth.uid() and theirs.user_id = target
  );
$$;

create or replace function private.my_group_ids()
returns setof uuid language sql stable security definer
set search_path = public, pg_temp
as $$ select group_id from public.group_members where user_id = auth.uid() $$;

create or replace function private.current_username()
returns text language sql stable security definer
set search_path = public, pg_temp
as $$ select username from public.profiles where user_id = auth.uid() $$;

create or replace function private.visible_active_pro_user_ids()
returns table(user_id uuid) language sql stable security definer
set search_path = public, private, pg_temp
as $$
  select p.user_id from public.pro_users p where private.pro_active(p.user_id)
    and (p.user_id=auth.uid() or private.shares_group_with(p.user_id))
$$;

grant execute on function private.pro_active(uuid) to authenticated;
grant execute on function private.shares_group_with(uuid) to authenticated;
grant execute on function private.my_group_ids() to authenticated;
grant execute on function private.current_username() to authenticated;
grant execute on function private.visible_active_pro_user_ids() to authenticated;

-- Keep usernames independent from login emails. Legacy users retain fake login emails;
-- new users use verified real emails and store their public username in metadata.
create or replace function private.sync_profile_from_auth()
returns trigger language plpgsql security definer
set search_path = public, auth, pg_temp
as $$
declare
  uname text := lower(coalesce(nullif(new.raw_user_meta_data->>'username',''), split_part(new.email,'@',1)));
  existing text;
begin
  if uname !~ '^[a-z0-9_]{3,20}$' then
    raise exception 'Username must be 3-20 lowercase letters, numbers, or underscores.';
  end if;
  if uname ~ '(nigg|fagg|kike|spic|chink|tranny)' then
    raise exception 'That username is not allowed.';
  end if;
  select username into existing from public.profiles where user_id = new.id;
  if existing is not null and existing <> uname then
    raise exception 'Usernames cannot be changed.';
  end if;
  insert into public.profiles(user_id, username, is_legacy, created_at)
  values (new.id, uname, new.email like '%@lifting.local', coalesce(new.created_at, now()))
  on conflict (user_id) do update set is_legacy = excluded.is_legacy;
  return new;
end;
$$;

drop trigger if exists trg_enforce_username on auth.users;
drop trigger if exists trg_sync_profile on auth.users;
create trigger trg_sync_profile
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function private.sync_profile_from_auth();

-- Daily private snapshots.
create or replace function private.snapshot_user_state()
returns trigger language plpgsql security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.user_state_history(user_id, day, value)
  values (old.user_id, current_date, old.value)
  on conflict (user_id, day) do nothing;
  delete from public.user_state_history
   where user_id = old.user_id and day < current_date - 30;
  return new;
end;
$$;
drop trigger if exists trg_snapshot_user_state on public.user_state;
create trigger trg_snapshot_user_state before update on public.user_state
for each row execute function private.snapshot_user_state();

-- Reaction names always come from the protected username directory.
create or replace function private.set_reactor_name()
returns trigger language plpgsql security definer
set search_path = public, pg_temp
as $$
begin
  new.reactor_id := auth.uid();
  select username into new.reactor_name from public.profiles where user_id = auth.uid();
  if new.reactor_name is null then raise exception 'Not signed in.'; end if;
  return new;
end;
$$;
drop trigger if exists trg_set_reactor_name on public.reactions;
create trigger trg_set_reactor_name before insert on public.reactions
for each row execute function private.set_reactor_name();

-- Return only data a group profile needs. Private journal/nutrition/routines/notes,
-- device settings, gym names, height and backups never leave the owner's row.
create or replace function private.shared_user_states(p_user_ids uuid[])
returns table(user_id uuid, value jsonb)
language sql stable security definer
set search_path = public, pg_temp
as $$
  select s.user_id,
    jsonb_strip_nulls(jsonb_build_object(
      'exercises', case when coalesce((s.value#>>'{profile,sharing,workouts}')::boolean, true)
                        then coalesce(s.value->'exercises','[]'::jsonb) else '[]'::jsonb end,
      'log', case when coalesce((s.value#>>'{profile,sharing,workouts}')::boolean, true) then
        coalesce((select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
          'id', e->'id', 'date', e->'date', 'exercise', e->'exercise', 'muscle', e->'muscle',
          'set', e->'set', 'sets', e->'sets', 'weight', e->'weight', 'reps', e->'reps',
          'effort', e->'effort', 'quick', e->'quick', 'muscleOnly', e->'muscleOnly',
          'quickSessionId', e->'quickSessionId', 'drops', e->'drops'
        ))) from jsonb_array_elements(coalesce(s.value->'log','[]'::jsonb)) e), '[]'::jsonb)
      else '[]'::jsonb end,
      'bodyweight', case when coalesce((s.value#>>'{profile,sharing,bodyweight}')::boolean, false) then
        coalesce((select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
          'date', b->'date', 'weight', b->'weight', 'creatine', b->'creatine'
        ))) from jsonb_array_elements(coalesce(s.value->'bodyweight','[]'::jsonb)) b), '[]'::jsonb)
      else '[]'::jsonb end,
      'cardio', case when coalesce((s.value#>>'{profile,sharing,cardio}')::boolean, true) then
        coalesce((select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
          'id', c->'id', 'date', c->'date', 'activity', c->'activity',
          'duration', c->'duration', 'calories', c->'calories', 'distance', c->'distance'
        ))) from jsonb_array_elements(coalesce(s.value->'cardio','[]'::jsonb)) c), '[]'::jsonb)
      else '[]'::jsonb end,
      'profile', jsonb_strip_nulls(jsonb_build_object(
        'theme', s.value#>'{profile,theme}',
        'stepGoal', s.value#>'{profile,stepGoal}',
        'setGoalMode', case when coalesce((s.value#>>'{profile,sharing,workouts}')::boolean, true) then s.value#>'{profile,setGoalMode}' end,
        'setTargets', case when coalesce((s.value#>>'{profile,sharing,workouts}')::boolean, true) then s.value#>'{profile,setTargets}' end,
        'strengthSetTargets', case when coalesce((s.value#>>'{profile,sharing,workouts}')::boolean, true) then s.value#>'{profile,strengthSetTargets}' end,
        'goalWeight', case when coalesce((s.value#>>'{profile,sharing,goals}')::boolean, false) then s.value#>'{profile,goalWeight}' end,
        'goalStartWeight', case when coalesce((s.value#>>'{profile,sharing,goals}')::boolean, false) then s.value#>'{profile,goalStartWeight}' end,
        'goalSetDate', case when coalesce((s.value#>>'{profile,sharing,goals}')::boolean, false) then s.value#>'{profile,goalSetDate}' end
      ))
    )) as value
  from public.user_state s
  where s.user_id = any(coalesce(p_user_ids, array[]::uuid[]))
    and (s.user_id = auth.uid() or private.shares_group_with(s.user_id));
$$;

grant execute on function private.shared_user_states(uuid[]) to authenticated;

-- Strong, single-use backup codes for legacy accounts and optional fallback for email users.
create or replace function private.generate_backup_codes()
returns table(code text) language plpgsql security definer
set search_path = public, private, extensions, pg_temp
as $$
declare raw text; i integer;
begin
  if auth.uid() is null then raise exception 'Not signed in.'; end if;
  delete from private.backup_codes where user_id = auth.uid();
  for i in 1..8 loop
    raw := upper(encode(extensions.gen_random_bytes(8), 'hex'));
    insert into private.backup_codes(user_id, code_hash)
    values (auth.uid(), extensions.crypt(raw, extensions.gen_salt('bf')));
    code := substr(raw,1,4)||'-'||substr(raw,5,4)||'-'||substr(raw,9,4)||'-'||substr(raw,13,4);
    return next;
  end loop;
end;
$$;

create or replace function private.has_backup_codes()
returns boolean language sql stable security definer
set search_path = private, pg_temp
as $$ select exists(select 1 from private.backup_codes where user_id=auth.uid() and used_at is null) $$;

create or replace function private.reset_password_with_backup_code(
  p_username text, p_code text, p_new_password text
) returns jsonb language plpgsql security definer
set search_path = public, private, auth, extensions, pg_temp
as $$
declare
  ident text := lower(trim(coalesce(p_username,'')));
  normalized text := upper(replace(trim(coalesce(p_code,'')),'-',''));
  uid uuid; matched_id bigint; attempts integer := 0; until_at timestamptz; cooldown interval;
begin
  if ident !~ '^[a-z0-9_]{3,20}$' or length(normalized) <> 16 or p_new_password is null or length(p_new_password) < 10 then
    return jsonb_build_object('ok',false,'code','invalid');
  end if;
  select failed_attempts, locked_until into attempts, until_at
    from private.recovery_attempts where identifier=ident;
  if until_at is not null and until_at > now() then
    return jsonb_build_object('ok',false,'code','slow_down','retry_after',ceil(extract(epoch from (until_at-now()))));
  end if;
  select user_id into uid from public.profiles where username=ident;
  if uid is not null then
    select id into matched_id from private.backup_codes b
     where b.user_id=uid and b.used_at is null
       and b.code_hash = extensions.crypt(normalized,b.code_hash)
     limit 1;
  else
    perform extensions.crypt(normalized, extensions.gen_salt('bf'));
  end if;
  if matched_id is null then
    attempts := coalesce(attempts,0)+1;
    cooldown := case when attempts >= 6 then interval '1 hour'
                     when attempts = 5 then interval '10 minutes'
                     when attempts = 4 then interval '2 minutes'
                     when attempts = 3 then interval '30 seconds'
                     else interval '0 seconds' end;
    insert into private.recovery_attempts(identifier,failed_attempts,locked_until,updated_at)
    values (ident,attempts,case when attempts>=3 then now()+cooldown else null end,now())
    on conflict(identifier) do update set failed_attempts=excluded.failed_attempts,
      locked_until=excluded.locked_until,updated_at=now();
    return jsonb_build_object('ok',false,'code',case when attempts>=3 then 'slow_down' else 'invalid' end,
      'retry_after',case when attempts>=3 then extract(epoch from cooldown)::integer else 0 end);
  end if;
  update private.backup_codes set used_at=now() where id=matched_id;
  delete from private.recovery_attempts where identifier=ident;
  update auth.users
     set encrypted_password=extensions.crypt(p_new_password,extensions.gen_salt('bf')),
         updated_at=now()
   where id=uid;
  delete from auth.sessions where user_id=uid;
  return jsonb_build_object('ok',true,'code','ok');
end;
$$;

grant execute on function private.generate_backup_codes() to authenticated;
grant execute on function private.has_backup_codes() to authenticated;
grant execute on function private.reset_password_with_backup_code(text,text,text) to anon, authenticated;

-- Group creation/joining with 128-bit invite codes and persistent throttling.
create or replace function private.create_group(p_name text)
returns table(group_id uuid, invite_code text) language plpgsql security definer
set search_path = public, extensions, pg_temp
as $$
declare gid uuid; code text; uname text;
begin
  if auth.uid() is null then raise exception 'Not signed in.'; end if;
  if p_name is null or length(trim(p_name)) < 1 or length(trim(p_name)) > 40 then
    raise exception 'Group name must be 1-40 characters.';
  end if;
  code := upper(encode(extensions.gen_random_bytes(16),'hex'));
  select username into uname from public.profiles where user_id=auth.uid();
  insert into public.groups(name,invite_code,created_by) values(trim(p_name),code,auth.uid()) returning id into gid;
  insert into public.group_members(group_id,user_id,username) values(gid,auth.uid(),uname);
  return query select gid,code;
end;
$$;

create or replace function private.join_group(p_code text)
returns jsonb language plpgsql security definer
set search_path = public, private, pg_temp
as $$
declare g record; uname text; attempts integer:=0; until_at timestamptz; cooldown interval;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'code','not_signed_in'); end if;
  select failed_attempts,locked_until into attempts,until_at from private.join_attempts where user_id=auth.uid();
  if until_at is not null and until_at>now() then
    return jsonb_build_object('ok',false,'code','slow_down','retry_after',ceil(extract(epoch from(until_at-now()))));
  end if;
  select id,name into g from public.groups where invite_code=upper(replace(trim(coalesce(p_code,'')),'-',''));
  if g.id is null then
    attempts:=coalesce(attempts,0)+1;
    cooldown:=case when attempts>=7 then interval '1 hour'
                   when attempts=6 then interval '15 minutes'
                   when attempts=5 then interval '5 minutes'
                   when attempts=4 then interval '1 minute'
                   when attempts=3 then interval '15 seconds'
                   else interval '0 seconds' end;
    insert into private.join_attempts(user_id,failed_attempts,locked_until,updated_at)
    values(auth.uid(),attempts,case when attempts>=3 then now()+cooldown else null end,now())
    on conflict(user_id) do update set failed_attempts=excluded.failed_attempts,
      locked_until=excluded.locked_until,updated_at=now();
    return jsonb_build_object('ok',false,'code',case when attempts>=3 then 'slow_down' else 'invalid' end,
      'retry_after',case when attempts>=3 then extract(epoch from cooldown)::integer else 0 end);
  end if;
  select username into uname from public.profiles where user_id=auth.uid();
  insert into public.group_members(group_id,user_id,username) values(g.id,auth.uid(),uname) on conflict do nothing;
  delete from private.join_attempts where user_id=auth.uid();
  return jsonb_build_object('ok',true,'group_id',g.id,'group_name',g.name);
end;
$$;

create or replace function private.reset_invite_code(p_group_id uuid)
returns text language plpgsql security definer set search_path=public,extensions,pg_temp as $$
declare code text;
begin
  if not exists(select 1 from public.groups where id=p_group_id and created_by=auth.uid()) then
    raise exception 'Only the group owner can reset the invite code.';
  end if;
  code:=upper(encode(extensions.gen_random_bytes(16),'hex'));
  update public.groups set invite_code=code where id=p_group_id;
  return code;
end;
$$;

create or replace function private.set_group_emoji(p_group_id uuid,p_emoji text)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if char_length(coalesce(p_emoji,''))<1 or char_length(p_emoji)>16 then raise exception 'Invalid emoji.'; end if;
  update public.groups g set emoji=p_emoji where g.id=p_group_id
    and exists(select 1 from public.group_members m where m.group_id=g.id and m.user_id=auth.uid());
  if not found then raise exception 'Not a member of this group.'; end if;
end;
$$;

create or replace function private.set_group_record_lifts(p_group_id uuid,p_lifts jsonb)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if p_lifts is not null and (jsonb_typeof(p_lifts)<>'array' or jsonb_array_length(p_lifts)>12) then
    raise exception 'Invalid lift list.';
  end if;
  update public.groups set record_lifts=p_lifts where id=p_group_id and created_by=auth.uid();
  if not found then raise exception 'Only the group owner can edit records.'; end if;
end;
$$;

grant execute on function private.create_group(text) to authenticated;
grant execute on function private.join_group(text) to authenticated;
grant execute on function private.reset_invite_code(uuid) to authenticated;
grant execute on function private.set_group_emoji(uuid,text) to authenticated;
grant execute on function private.set_group_record_lifts(uuid,jsonb) to authenticated;

-- Apple Health token is a revocable bearer secret. Only active Pro accounts can
-- create/use one; users can rotate it or disconnect and delete their step history.
create or replace function private.my_step_token()
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare t uuid;
begin
  if auth.uid() is null or not private.pro_active(auth.uid()) then raise exception 'Pro required.'; end if;
  insert into public.step_tokens(user_id) values(auth.uid()) on conflict(user_id) do nothing;
  select token into t from public.step_tokens where user_id=auth.uid(); return t;
end;
$$;

create or replace function private.rotate_step_token()
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare t uuid:=gen_random_uuid();
begin
  if auth.uid() is null or not private.pro_active(auth.uid()) then raise exception 'Pro required.'; end if;
  insert into public.step_tokens(user_id,token,created_at) values(auth.uid(),t,now())
  on conflict(user_id) do update set token=excluded.token,created_at=now(); return t;
end;
$$;

create or replace function private.disconnect_steps(p_delete_data boolean default true)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if auth.uid() is null then raise exception 'Not signed in.'; end if;
  delete from public.step_tokens where user_id=auth.uid();
  if coalesce(p_delete_data,true) then delete from public.steps where user_id=auth.uid(); end if;
end;
$$;

create or replace function private.log_steps(p_token uuid,p_day date,p_count integer)
returns text language plpgsql security definer set search_path=public,pg_temp as $$
declare uid uuid;
begin
  if p_count is null or p_count<0 or p_count>=1000000 then return 'bad count'; end if;
  select t.user_id into uid from public.step_tokens t where t.token=p_token;
  if uid is null or not private.pro_active(uid) then return 'bad token'; end if;
  if p_day is null or p_day<current_date-15 or p_day>current_date+1 then return 'bad date'; end if;
  insert into public.steps(user_id,day,count,updated_at) values(uid,p_day,p_count,now())
  on conflict(user_id,day) do update set count=excluded.count,updated_at=now();
  return 'ok';
end;
$$;

grant execute on function private.my_step_token() to authenticated;
grant execute on function private.rotate_step_token() to authenticated;
grant execute on function private.disconnect_steps(boolean) to authenticated;
grant execute on function private.log_steps(uuid,date,integer) to anon,authenticated;

-- Duels: participants no longer get arbitrary UPDATE rights. Every transition has
-- a narrow server-side command and derives names/winner from trusted rows.
create or replace function private.duel_create(p_b_id uuid,p_days integer)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare did uuid; an text; bn text; d integer:=greatest(1,least(30,coalesce(p_days,7)));
begin
  if auth.uid() is null or not private.pro_active(auth.uid()) or not private.pro_active(p_b_id) then raise exception 'Both people need Pro.'; end if;
  if p_b_id=auth.uid() or not private.shares_group_with(p_b_id) then raise exception 'You can only challenge a groupmate.'; end if;
  select username into an from public.profiles where user_id=auth.uid();
  select username into bn from public.profiles where user_id=p_b_id;
  insert into public.duels(a_id,b_id,a_name,b_name,start_day,end_day,days,status)
  values(auth.uid(),p_b_id,an,bn,current_date,current_date+d-1,d,'pending') returning id into did;
  return did;
end;
$$;

create or replace function private.duel_accept(p_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare d integer;
begin
  select greatest(1,least(30,coalesce(days,7))) into d from public.duels where id=p_id and b_id=auth.uid() and status='pending';
  if d is null then raise exception 'Only the challenged person can accept a pending duel.'; end if;
  update public.duels set status='active',start_day=current_date,end_day=current_date+d-1 where id=p_id;
end;
$$;

create or replace function private.duel_decline(p_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  update public.duels set status='declined' where id=p_id and b_id=auth.uid() and status='pending';
  if not found then raise exception 'Only the challenged person can decline.'; end if;
end;
$$;

create or replace function private.duel_forfeit(p_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  update public.duels set status='forfeited',winner_id=case when a_id=auth.uid() then b_id else a_id end,cancel_req=null
   where id=p_id and status='active' and auth.uid() in(a_id,b_id);
  if not found then raise exception 'Active duel not found.'; end if;
end;
$$;

create or replace function private.duel_request_cancel(p_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  update public.duels set cancel_req=auth.uid() where id=p_id and status='active' and auth.uid() in(a_id,b_id);
  if not found then raise exception 'Active duel not found.'; end if;
end;
$$;

create or replace function private.duel_clear_cancel(p_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  update public.duels set cancel_req=null where id=p_id and status='active' and auth.uid() in(a_id,b_id);
  if not found then raise exception 'Active duel not found.'; end if;
end;
$$;

create or replace function private.duel_delete(p_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  delete from public.duels d where d.id=p_id and auth.uid() in(d.a_id,d.b_id) and (
    d.status in('declined','completed','forfeited') or
    (d.status='pending' and (auth.uid()=d.a_id or auth.uid()=d.b_id)) or
    (d.status='active' and d.cancel_req is not null and d.cancel_req<>auth.uid())
  );
  if not found then raise exception 'This duel cannot be removed yet.'; end if;
end;
$$;

grant execute on function private.duel_create(uuid,integer) to authenticated;
grant execute on function private.duel_accept(uuid) to authenticated;
grant execute on function private.duel_decline(uuid) to authenticated;
grant execute on function private.duel_forfeit(uuid) to authenticated;
grant execute on function private.duel_request_cancel(uuid) to authenticated;
grant execute on function private.duel_clear_cancel(uuid) to authenticated;
grant execute on function private.duel_delete(uuid) to authenticated;

create or replace function private.delete_my_account()
returns void language plpgsql security definer set search_path=auth,public,pg_temp as $$
begin
  if auth.uid() is null then raise exception 'Not signed in.'; end if;
  delete from auth.users where id=auth.uid();
end;
$$;
grant execute on function private.delete_my_account() to authenticated;

-- ---------------------------------------------------------------------------
-- Narrow public RPC surface. These wrappers do not themselves bypass RLS.
-- ---------------------------------------------------------------------------

create or replace function public.get_shared_user_states(p_user_ids uuid[])
returns table(user_id uuid,value jsonb) language sql stable security invoker
set search_path=private,public,pg_temp as $$ select * from private.shared_user_states(p_user_ids) $$;
create or replace function public.generate_backup_codes()
returns table(code text) language sql volatile security invoker
set search_path=private,pg_temp as $$ select * from private.generate_backup_codes() $$;
create or replace function public.has_backup_codes()
returns boolean language sql stable security invoker
set search_path=private,pg_temp as $$ select private.has_backup_codes() $$;
create or replace function public.reset_password_with_backup_code(p_username text,p_code text,p_new_password text)
returns jsonb language sql volatile security invoker
set search_path=private,pg_temp as $$ select private.reset_password_with_backup_code(p_username,p_code,p_new_password) $$;
create or replace function public.create_group(p_name text)
returns table(group_id uuid,invite_code text) language sql volatile security invoker
set search_path=private,pg_temp as $$ select * from private.create_group(p_name) $$;
drop function if exists public.join_group(text);
create or replace function public.join_group(p_code text)
returns jsonb language sql volatile security invoker
set search_path=private,pg_temp as $$ select private.join_group(p_code) $$;
create or replace function public.reset_invite_code(p_group_id uuid)
returns text language sql volatile security invoker
set search_path=private,pg_temp as $$ select private.reset_invite_code(p_group_id) $$;
create or replace function public.set_group_emoji(p_group_id uuid,p_emoji text)
returns void language sql volatile security invoker
set search_path=private,pg_temp as $$ select private.set_group_emoji(p_group_id,p_emoji) $$;
create or replace function public.set_group_record_lifts(p_group_id uuid,p_lifts jsonb)
returns void language sql volatile security invoker
set search_path=private,pg_temp as $$ select private.set_group_record_lifts(p_group_id,p_lifts) $$;
create or replace function public.my_pro_active()
returns boolean language sql stable security invoker
set search_path=private,pg_temp as $$ select private.pro_active(auth.uid()) $$;
create or replace function public.visible_active_pro_user_ids()
returns table(user_id uuid) language sql stable security invoker
set search_path=private,pg_temp as $$ select * from private.visible_active_pro_user_ids() $$;
create or replace function public.my_step_token()
returns uuid language sql volatile security invoker set search_path=private,pg_temp as $$ select private.my_step_token() $$;
create or replace function public.rotate_step_token()
returns uuid language sql volatile security invoker set search_path=private,pg_temp as $$ select private.rotate_step_token() $$;
create or replace function public.disconnect_steps(p_delete_data boolean default true)
returns void language sql volatile security invoker set search_path=private,pg_temp as $$ select private.disconnect_steps(p_delete_data) $$;
create or replace function public.log_steps(p_token uuid,p_day date,p_count integer)
returns text language sql volatile security invoker set search_path=private,pg_temp as $$ select private.log_steps(p_token,p_day,p_count) $$;
create or replace function public.duel_create(p_b_id uuid,p_days integer)
returns uuid language sql volatile security invoker set search_path=private,pg_temp as $$ select private.duel_create(p_b_id,p_days) $$;
create or replace function public.duel_accept(p_id uuid)
returns void language sql volatile security invoker set search_path=private,pg_temp as $$ select private.duel_accept(p_id) $$;
create or replace function public.duel_decline(p_id uuid)
returns void language sql volatile security invoker set search_path=private,pg_temp as $$ select private.duel_decline(p_id) $$;
create or replace function public.duel_forfeit(p_id uuid)
returns void language sql volatile security invoker set search_path=private,pg_temp as $$ select private.duel_forfeit(p_id) $$;
create or replace function public.duel_request_cancel(p_id uuid)
returns void language sql volatile security invoker set search_path=private,pg_temp as $$ select private.duel_request_cancel(p_id) $$;
create or replace function public.duel_clear_cancel(p_id uuid)
returns void language sql volatile security invoker set search_path=private,pg_temp as $$ select private.duel_clear_cancel(p_id) $$;
create or replace function public.duel_delete(p_id uuid)
returns void language sql volatile security invoker set search_path=private,pg_temp as $$ select private.duel_delete(p_id) $$;
create or replace function public.delete_my_account()
returns void language sql volatile security invoker set search_path=private,pg_temp as $$ select private.delete_my_account() $$;

-- Existing safe backup listing remains invoker/RLS-based.
create or replace function public.list_state_history()
returns table(day date,sets integer,weighins integer,cardio integer)
language sql security invoker set search_path=public,pg_temp as $$
  select day,coalesce(jsonb_array_length(value->'log'),0),
    coalesce(jsonb_array_length(value->'bodyweight'),0),coalesce(jsonb_array_length(value->'cardio'),0)
  from public.user_state_history where user_id=auth.uid() order by day desc
$$;

-- Remove the vulnerable security-question recovery surface and obsolete exposed helpers.
drop function if exists public.get_security_question(text);
drop function if exists public.set_security_question(text,text);
drop function if exists public.reset_password_with_answer(text,text,text);
-- Keep the old hashes quarantined for emergency rollback only; they are no longer in
-- the exposed API schema and no application role has access. Delete after the rollout
-- window once legacy members have saved backup codes.
do $$ begin
  if to_regclass('public.security_questions') is not null then
    alter table public.security_questions set schema private;
    alter table private.security_questions rename to legacy_security_questions_quarantine;
  end if;
end $$;
do $$ begin
  if to_regclass('private.legacy_security_questions_quarantine') is not null then
    execute 'revoke all on table private.legacy_security_questions_quarantine from public,anon,authenticated';
  end if;
end $$;
drop function if exists public.enforce_username();
drop function if exists public.set_reactor_name();
drop function if exists public.snapshot_user_state();

-- Rotate every existing short invite code immediately.
update public.groups set invite_code=upper(encode(extensions.gen_random_bytes(16),'hex'))
where length(invite_code)<32;

-- ---------------------------------------------------------------------------
-- RLS and least-privilege grants.
-- ---------------------------------------------------------------------------

alter table public.user_state enable row level security;
alter table public.user_state_history enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.pro_users enable row level security;
alter table public.steps enable row level security;
alter table public.step_tokens enable row level security;
alter table public.duels enable row level security;
alter table public.reactions enable row level security;
alter table public.profiles enable row level security;

drop policy if exists "users read own or groupmates" on public.user_state;
drop policy if exists "users read own" on public.user_state;
create policy "users read own" on public.user_state for select to authenticated using(auth.uid()=user_id);

drop policy if exists "read fellow members" on public.group_members;
create policy "read fellow members" on public.group_members for select to authenticated
using(group_id in(select private.my_group_ids()));

drop policy if exists "members read their groups" on public.groups;
create policy "members read their groups" on public.groups for select to authenticated
using(id in(select private.my_group_ids()));
drop policy if exists "groups_member_update" on public.groups;

drop policy if exists "pro_select" on public.pro_users;
drop policy if exists "step_tokens_own" on public.step_tokens;
drop policy if exists "steps_select" on public.steps;
create policy "steps_select" on public.steps for select to authenticated using(
  auth.uid()=user_id or (
    private.pro_active(auth.uid()) and private.pro_active(user_id) and private.shares_group_with(user_id)
  )
);

drop policy if exists "duels_insert" on public.duels;
drop policy if exists "duels_update" on public.duels;
drop policy if exists "duels_delete" on public.duels;
drop policy if exists "duels_select" on public.duels;
create policy "duels_select" on public.duels for select to authenticated using(
  auth.uid() in(a_id,b_id) or private.shares_group_with(a_id) or private.shares_group_with(b_id)
);

drop policy if exists "profiles_own" on public.profiles;
create policy "profiles_own" on public.profiles for select to authenticated using(user_id=auth.uid());

-- Rewrite policies that used the old exposed helper.
drop policy if exists "react in my groups" on public.reactions;
create policy "react in my groups" on public.reactions for insert to authenticated
with check(reactor_id=auth.uid() and group_id in(select private.my_group_ids()));
drop policy if exists "read group reactions" on public.reactions;
create policy "read group reactions" on public.reactions for select to authenticated
using(group_id in(select private.my_group_ids()));

-- Old helpers can now be removed after dependent policies have been replaced.
drop function if exists public.shares_group_with(uuid);
drop function if exists public.my_group_ids();

revoke all on all tables in schema public from anon;
revoke all on public.user_state,public.user_state_history,public.groups,public.group_members,
  public.pro_users,public.steps,public.step_tokens,public.duels,public.reactions,public.profiles from authenticated;
grant select,insert,update on public.user_state to authenticated;
grant select on public.user_state_history,public.groups,public.group_members,public.steps,public.duels,public.reactions to authenticated;
grant delete on public.group_members to authenticated;
grant insert,delete on public.reactions to authenticated;
grant select on public.profiles to authenticated;

-- Functions are closed by default, then only the intended API is opened.
revoke execute on all functions in schema public from public,anon,authenticated;
grant execute on function public.get_shared_user_states(uuid[]) to authenticated;
grant execute on function public.generate_backup_codes() to authenticated;
grant execute on function public.has_backup_codes() to authenticated;
grant execute on function public.reset_password_with_backup_code(text,text,text) to anon,authenticated;
grant execute on function public.create_group(text) to authenticated;
grant execute on function public.join_group(text) to authenticated;
grant execute on function public.reset_invite_code(uuid) to authenticated;
grant execute on function public.set_group_emoji(uuid,text) to authenticated;
grant execute on function public.set_group_record_lifts(uuid,jsonb) to authenticated;
grant execute on function public.my_pro_active() to authenticated;
grant execute on function public.visible_active_pro_user_ids() to authenticated;
grant execute on function public.my_step_token(),public.rotate_step_token(),public.disconnect_steps(boolean) to authenticated;
grant execute on function public.log_steps(uuid,date,integer) to anon,authenticated;
grant execute on function public.duel_create(uuid,integer),public.duel_accept(uuid),public.duel_decline(uuid),
  public.duel_forfeit(uuid),public.duel_request_cancel(uuid),public.duel_clear_cancel(uuid),public.duel_delete(uuid) to authenticated;
grant execute on function public.delete_my_account(),public.list_state_history() to authenticated;

commit;
